### ISSUE TITLE
Prevent Blank Posts from Being Accepted

### ISSUE THREAD

**Issue by manthanmk66** [Madan2468/Social-media-website#11]
The current form accepts blank posts, leading to empty submissions. This issue should add validation to prevent users from submitting a post without content.

**Comment by Madan2468** [comment]
You can start working on this , I have assigned this issue to you. Do starred this repo.

**Comment by manthanmk66** [comment]
Can you please add Hactoberfest Label

**Comment by Madan2468** [comment]
when your PR will get merged I will add with Hacktoberfest accepted label.
